version: '3.8'

services:
  db:
    image: postgres:14.3-alpine
    ports:
      - "5433:5434"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DB}