version: '3.8'

services:
  db:
    image: postgres:16-alpine
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app-network

  fastapi:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    networks:
      - app-network
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"

networks:
  app-network:
    driver: bridge
